---
env:
  - GO111MODULE=on
  - LINUXBENCH_CFG=/etc/windows-bench/cfg

builds:
  - main: .
    binary: windows-bench
    goos:
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ldflags:
      - "-X github.com/aquasecurity/windows-bench/root.cfgDir={{.Env.LINUXBENCH_CFG}}"
# Archive customization
archives:
  - id: compress
    format: zip
    name_template: "{{ .Binary }}_{{.Version}}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}"
    files:
      - "cfg/**/*"
