name: release
on:
  push:
    tags:
      - "v*"
jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run unit tests
        run: make tests
      - name: Release
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.7.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
