name: snapshot
on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
jobs:
  release-snapshot:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Dry-run release snapshot
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.7.0
          args: release --snapshot --skip-publish --rm-dist
